name: Deploy Azure Functions

on:
  push:
    paths-ignore:
      - "README.md"

env:
  AZURE_FUNCTIONAPP_NAME: arsenalextractor-2209-func # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: "6.0.401" # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub action"
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build ./src/ArsenalExtractor.Functions/src/ArsenalExtractor.csproj --configuration Release --output ./output
          popd
      - name: Unit Tests
        run: |
          dotnet restore ./src/ArsenalExtractor.Functions/tests/unit-tests/unit-tests.csproj
          dotnet test ./src/ArsenalExtractor.Functions/tests/unit-tests/unit-tests.csproj --no-restore --verbosity normal
      - name: "Run Azure Functions action"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
